spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Arogya
spring.datasource.username=root
spring.datasource.password=Gojo_Satoru111
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



##To set a Common API prefix for all endpoints
#server.servlet.context-path=/api/v1
